/**
 * 
 */
package com.patsage.microservices.user;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * @author dprakash
 *  * An entity User composed by three fields (username, firstname, lastname, password).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 */

@Entity
@Table(name = "ps_user")
public class Users {
	
	// An autogenerated id (unique for each user in the db)
	@Id
	//@GeneratedValue(strategy = GenerationType.AUTO)
	private long Id;
	
	// The user's code
	@NotNull
	private String username;
	
	// The user's first name
	@NotNull
	private String firstname;
	  
	// The user's last name
	@NotNull
	private String lastname;
	  
	// The user's password
	@NotNull
	private String password;

	// ------------------------
	// PUBLIC METHODS
	// ------------------------
	  
	public Users() { }
	
	public Users(long id) { 
	    this.Id = id;
	}
	
	public Users(String username) { 
	    this.username = username;
	}
	
	public Users( String username, String firstname, String lastname, 
			  		String password) {
		    this.username = username;
		    this.firstname = firstname;
		    this.lastname = lastname;
		    this.password = password;
	}
	
	// Getter and setter methods

	public long getId() {
		return Id;
	}
	  
	public void setId(long value) {
		this.Id = value;
	}
	
	public String getUserName() {
		return username;
	}
	  
	public void setUserName(String value) {
		this.username = value;
	}
	  
	public String getFirstName() {
		return firstname;
	}
	  
	public void setFirstName(String value) {
		this.firstname = value;
	}
	
	public String getLastName() {
		return lastname;
	}
	  
	public void setLastName(String value) {
		this.lastname = value;
	}
	
	public String getPassword() {
		return password;
	}
	  
	public void setPassword(String value) {
		this.password = value;
	}
	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
