# Spring properties
spring:
  application:
     name: web-service
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/web-server/templates/    # Trailing / mandatory
                       # Template location for this application only
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/patsage?autoReconnect=true&useSSL=false

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port
  
# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
         web: DEBUG
      hibernate: ERROR
      
 # instance info for patentsview.org

#patentsview-service:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: patentsview.org
#    ServerListRefreshInterval: 15000